//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodasat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposited
    {
        public int Id { get; set; }
        public string NationalID { get; set; }
        public string fullName { get; set; }
        public int kodasID { get; set; }
        public System.DateTime AttendedOn { get; set; }
        public Nullable<int> FatherID { get; set; }
        public Nullable<int> churchesID { get; set; }
        public Nullable<int> NumberFriends { get; set; }
    
        public virtual Church Church { get; set; }
        public virtual Login Login { get; set; }
        public virtual Koda Koda { get; set; }
    }
}
